### ISSUE TITLE
Is the Context name correct?

### ISSUE THREAD

**Issue by xyzpda** [aspnet/AspNetCore.Docs.ja-jp#289] opened 2020-02-04 01:51 UTC
https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#use-sqlite-for-development-sql-server-for-production

RazorPagesMovieContext, not MovieContext?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [ASP.NET Core での Razor ページ アプリへのモデルの追加](https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2020-02-04 03:16
Duplicate of #16720, recommend closing.

**Comment by srvbpigh** [comment] 2020-02-04 03:46
Hello, @xyzpda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment] 2020-02-04 18:50
Hello, @xyzpda,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged. 

Please review issue #https://github.com/aspnet/AspNetCore.Docs/issues/16720. For this reason we are closing this issue since it is duplicated. 

Kind regards, 

Microsoft DOCS International Team

**Closed by ticianaciminari** 2020-02-04 18:50 UTC
Labels: duplicate
